FROM node:18-alpine AS base

# Install only essential build dependencies
RUN apk add --no-cache python3 make g++ libc6-compat

# Install pnpm
RUN npm install -g pnpm@7.30.0

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./
COPY postcss.config.mjs tailwind.config.ts ./

# Install dependencies and update lockfile
RUN pnpm install --frozen-lockfile --production=false

# Copy the rest of the application
COPY . .

# Set up environment for build
RUN --mount=type=secret,id=openai_key \
    --mount=type=secret,id=hume_key \
    --mount=type=secret,id=hume_secret \
    echo "OPENAI_API_KEY=$(cat /run/secrets/openai_key)" > .env.local && \
    echo "HUME_API_KEY=$(cat /run/secrets/hume_key)" >> .env.local && \
    echo "HUME_SECRET_KEY=$(cat /run/secrets/hume_secret)" >> .env.local

# Build the application
RUN pnpm build

# Create a new stage for the final image
FROM node:18-alpine AS runner
WORKDIR /app

# Copy the standalone output from the build stage
COPY --from=base /app/.next/standalone ./
COPY --from=base /app/.next/static ./.next/static
COPY --from=base /app/public ./public

# Create tmp directory for audio processing
RUN mkdir -p tmp && chmod 777 tmp

# Production runtime configuration
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

EXPOSE 3000

# Start the application using the server.js generated by Next.js
CMD ["node", "server.js"]